openapi: 3.0.3
info:
  title: CAB System API - Xem cước chuyến
  description: API Xem cước chuyến.
  version: 1.0.0
servers:
- url: http://localhost:8080/api/v1
  description: Local server
tags:
- name: Authentication
- name: Customer
- name: Driver
- name: Trip
- name: Payment
- name: Rating
- name: Operator
- name: Report
paths:
  /trips/{trip_id}/fare:
    get:
      tags:
      - Payment
      summary: Xem cước chuyến
      parameters:
      - name: trip_id
        in: path
        required: true
        description: ID của trip_id
        schema:
          type: string
      responses:
        '200':
          description: Thông tin cước
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FareResponse'
components:
  schemas:
    FareResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            trip_id:
              type: string
            currency:
              type: string
              example: VND
            amount:
              type: number
            status:
              type: string
